### ISSUE TITLE
Nano x SDK missing

### ISSUE THREAD

**Issue by Ram-sankar-A-S-K** [LedgerHQ/ledger-app-boilerplate#2]
you have mentioned nanox-secure-sdk in dev-env. But that was not installed and setup. I am searching for the nano x SDK. I cant able to figure out. Please provide nanox-secure-sdk

**Comment by afsym** [comment]
Hello,
The nano x secure sdk is not available for external developers yet unfortunately.
This part of the script is only intended for internal devs for the moment, but we will communicate when it's available :)

**Comment by Ram-sankar-A-S-K** [comment]
Thanks :)
