### ISSUE TITLE
nano x sdk 

### ISSUE THREAD

**Issue by ccccbjcn** [LedgerHQ/ledger-app-boilerplate#4]
https://github.com/LedgerHQ/ledger-app-boilerplate/blob/d46d671d00cb01798934633d25a6dad5f910ff1c/prepare-devenv.sh#L77

 @TamtamHero 
How to setup nano x sdk?

**Comment by afsym** [comment]
Hello,
The nano x secure sdk is not available for external developers yet unfortunately.
This part of the script is only intended for internal devs for the moment, but we will communicate when it's available :)

**Comment by ccccbjcn** [comment]
@afsym Whether we should use nano x secure sdk to integrate new blockchain in Nano X device?
I am NULS community developer, could you give me the schedule time for opening nano x secure sdk  to external developers?
Thanks.

**Comment by afsym** [comment]
Since you're NULS community developer, are you part of the Ledger Slack-dev by any chance?

**Comment by ccccbjcn** [comment]
@afsym  I am working part time in NULS community. Could you invite me into ledger-dev.slack.com, then I could get some helps from your team for NULS integration. Could you give me your Telegram ID?

**Comment by afsym** [comment]
@ccccbjcn I just need an email address from you, to get you on said Slack :)
Would you like it to be cccbjcn@163.com ?

**Comment by ccccbjcn** [comment]
@afsym  cccbjcn@163.com is fine. thanks.

**Comment by ccccbjcn** [comment]
@afsym  I have participated ledger-dev Slack channel.
Thanks for your invitation.

**Comment by brainfrog** [comment]
> Hello,
> The nano x secure sdk is not available for external developers yet unfortunately.
> This part of the script is only intended for internal devs for the moment, but we will communicate when it's available :)

Hello @afsym. I'm developing a Free TON Nano X application. Can you please invite m.a.vladykin+ledger@gmail.com to ledger developer Slack?
